# Generated by Django 5.0.6 on 2024-06-18 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('auspiciante', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CampeonatoEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campeonatosequipo', to='futbolec.campeonato')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('siglas', models.CharField(max_length=30)),
                ('twitter', models.CharField(blank=True, max_length=30)),
                ('campeonatos', models.ManyToManyField(related_name='equipos_participantes', through='futbolec.CampeonatoEquipos', to='futbolec.campeonato')),
            ],
        ),
        migrations.AddField(
            model_name='campeonatoequipos',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campeonatosequipo', to='futbolec.equipo'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='equipos',
            field=models.ManyToManyField(related_name='campeonatos_participados', through='futbolec.CampeonatoEquipos', to='futbolec.equipo'),
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('posicion', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
                ('sueldo', models.FloatField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolec.equipo')),
            ],
        ),
    ]
